import type { Mode } from "./brief.ts";
import { DEFAULT_MODEL, DEFAULT_REPORT, DEFAULT_SCOPE } from "./brief-defaults.ts";

/** A front-matter template for `zai brief new`: every field documented, mode-specific defaults written out. */
export function renderBriefTemplate(title: string, mode: Mode): string {
  return [
    "---",
    "# Short name shown on the board and in commit messages.",
    `title: ${JSON.stringify(title)}`,
    "# edit: own git worktree and branch zai/<id>; the worker may change files inside scope.",
    "# exec: may run commands but must not change the repository; outputs go to $ZAI_ARTIFACTS.",
    "# readonly: plan mode, read tools only.",
    `mode: ${mode}`,
    "# glm (glm-5.3) or flash (glm-5.3-flash). Default: glm for edit, flash otherwise.",
    `model: ${DEFAULT_MODEL[mode]}`,
    "# low | medium | high, passed to claude --effort. Default: unset.",
    "# effort: medium",
    "# Repository the job works on; a relative path resolves against the default, the current git root.",
    "# cwd: .",
    "# Ref the worktree starts from.",
    "base: HEAD",
    "# Globs the change set may touch (picomatch, dotfiles included). Default: everything for edit, nothing otherwise.",
    `scope: ${JSON.stringify(DEFAULT_SCOPE[mode])}`,
    "# Globs that must stay untouched even inside scope.",
    "forbid: []",
    "# Shell commands the plugin runs in the workspace after the worker, each a string or {run, timeout} (default 10m).",
    "# Example: [npm test, { run: npm run lint, timeout: 5m }]",
    "gates: []",
    "# Per attempt: 90s, 15m, 2h, 1h30m or milliseconds.",
    "timeout: 2h",
    "# fix: auto-fix rounds after a failed verdict; infra: re-runs after infrastructure errors.",
    "retries: { fix: 1, infra: 2 }",
    "# Report contract: change, sweep, notes or a path to a JSON schema file. Default: by mode.",
    `report: ${DEFAULT_REPORT[mode]}`,
    "# Extra readable paths, passed as --add-dir.",
    "addDirs: []",
    "# Names of orchestrator environment variables passed to the worker and gates; values are never stored.",
    "env: []",
    "# Spending cap in USD, passed as --max-budget-usd. Default: unset.",
    "# budgetUsd: 2",
    "# Free labels for batches and board filters.",
    "tags: []",
    "---",
    "TODO: describe the task for the worker: what to change, where, and what done looks like.",
    "",
  ].join("\n");
}
